//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LcsSaveEditor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LcsSaveEditor.Resources.CommonResources", typeof(CommonResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;block size&apos; field in the block header is greater than the number of available bytes in the stream. BlockSize = {0}, AvailableBytes = {1}..
        /// </summary>
        public static string Error_BadBlockSize {
            get {
                return ResourceManager.GetString("Error_BadBlockSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect block tag - &apos;{0}&apos;. Expected &apos;{1}&apos;..
        /// </summary>
        public static string Error_BadBlockTag {
            get {
                return ResourceManager.GetString("Error_BadBlockTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConvertBack is not supported for this converter..
        /// </summary>
        public static string Error_ConvertBackNotSupported {
            get {
                return ResourceManager.GetString("Error_ConvertBackNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;block size&apos; field in the block header does not match the number of bytes read. BlockSize = {0}, BytesRead = {1}..
        /// </summary>
        public static string Error_IncorrectBlockSize {
            get {
                return ResourceManager.GetString("Error_IncorrectBlockSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid GTA:LCS save data fle..
        /// </summary>
        public static string Error_InvalidGtaSaveData {
            get {
                return ResourceManager.GetString("Error_InvalidGtaSaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received a PropertyChanged notification from an item not in the collection..
        /// </summary>
        public static string Error_InvalidPropertyChanged {
            get {
                return ResourceManager.GetString("Error_InvalidPropertyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load failed..
        /// </summary>
        public static string Error_LoadFail {
            get {
                return ResourceManager.GetString("Error_LoadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple calls to this function are not supported. ({0}()).
        /// </summary>
        public static string Error_MultipleCallsNotSupported {
            get {
                return ResourceManager.GetString("Error_MultipleCallsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You weren&apos;t supposed to be able to get here, you know. ({0}()).
        /// </summary>
        public static string Error_Oops {
            get {
                return ResourceManager.GetString("Error_Oops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save failed..
        /// </summary>
        public static string Error_SaveFail {
            get {
                return ResourceManager.GetString("Error_SaveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load settings. Using default settings..
        /// </summary>
        public static string Error_SettingsLoadFailUseDefault {
            get {
                return ResourceManager.GetString("Error_SettingsLoadFailUseDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save settings..
        /// </summary>
        public static string Error_SettingsSaveFail {
            get {
                return ResourceManager.GetString("Error_SettingsSaveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is a static array; it cannot be resized..
        /// </summary>
        public static string Error_StaticArrayResize {
            get {
                return ResourceManager.GetString("Error_StaticArrayResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load symbols..
        /// </summary>
        public static string Error_SymbolsLoadFail {
            get {
                return ResourceManager.GetString("Error_SymbolsLoadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save symbols..
        /// </summary>
        public static string Error_SymbolsSaveFail {
            get {
                return ResourceManager.GetString("Error_SymbolsSaveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exiting....
        /// </summary>
        public static string Info_AppExit {
            get {
                return ResourceManager.GetString("Info_AppExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File closed..
        /// </summary>
        public static string Info_FileClosed {
            get {
                return ResourceManager.GetString("Info_FileClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File format: {0}.
        /// </summary>
        public static string Info_FileFormat {
            get {
                return ResourceManager.GetString("Info_FileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size: {0} bytes.
        /// </summary>
        public static string Info_FileSize {
            get {
                return ResourceManager.GetString("Info_FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File type unknown..
        /// </summary>
        public static string Info_FileTypeUnknown {
            get {
                return ResourceManager.GetString("Info_FileTypeUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading GTA:LCS save data....
        /// </summary>
        public static string Info_LoadingGtaData {
            get {
                return ResourceManager.GetString("Info_LoadingGtaData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading settings....
        /// </summary>
        public static string Info_LoadingSettings {
            get {
                return ResourceManager.GetString("Info_LoadingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading UI....
        /// </summary>
        public static string Info_LoadingUI {
            get {
                return ResourceManager.GetString("Info_LoadingUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load successful..
        /// </summary>
        public static string Info_LoadSuccess {
            get {
                return ResourceManager.GetString("Info_LoadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading &apos;{0}&apos; block....
        /// </summary>
        public static string Info_ReadingBlock {
            get {
                return ResourceManager.GetString("Info_ReadingBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready..
        /// </summary>
        public static string Info_Ready {
            get {
                return ResourceManager.GetString("Info_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save successful..
        /// </summary>
        public static string Info_SaveSuccess {
            get {
                return ResourceManager.GetString("Info_SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving GTA:LCS save data....
        /// </summary>
        public static string Info_SavingGtaData {
            get {
                return ResourceManager.GetString("Info_SavingGtaData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving settings....
        /// </summary>
        public static string info_SavingSettings {
            get {
                return ResourceManager.GetString("info_SavingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbols loaded..
        /// </summary>
        public static string Info_SymbolsLoadSuccess {
            get {
                return ResourceManager.GetString("Info_SymbolsLoadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbols saved..
        /// </summary>
        public static string Info_SymbolsSaveSuccess {
            get {
                return ResourceManager.GetString("Info_SymbolsSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing &apos;{0}&apos; block....
        /// </summary>
        public static string Info_WritingBlock {
            get {
                return ResourceManager.GetString("Info_WritingBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing padding,,,.
        /// </summary>
        public static string Info_WritingPadding {
            get {
                return ResourceManager.GetString("Info_WritingPadding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings not found! Using default settings..
        /// </summary>
        public static string Warn_SettingsNotFoundUseDefault {
            get {
                return ResourceManager.GetString("Warn_SettingsNotFoundUseDefault", resourceCulture);
            }
        }
    }
}
