//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LcsSaveEditor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FrontendResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FrontendResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LcsSaveEditor.Resources.FrontendResources", typeof(FrontendResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About_Window_Title {
            get {
                return ResourceManager.GetString("About_Window_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thehambone.
        /// </summary>
        public static string App_Author {
            get {
                return ResourceManager.GetString("App_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wes Hampson.
        /// </summary>
        public static string App_AuthorAlternate {
            get {
                return ResourceManager.GetString("App_AuthorAlternate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thehambone93@gmail.com.
        /// </summary>
        public static string App_AuthorContact {
            get {
                return ResourceManager.GetString("App_AuthorContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (C) 2016-2019 Wes Hampson. All Rights Reserved..
        /// </summary>
        public static string App_Copyright {
            get {
                return ResourceManager.GetString("App_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand Theft Auto: Liberty City Stories savegame editor..
        /// </summary>
        public static string App_Description {
            get {
                return ResourceManager.GetString("App_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTA:LCS Save Editor.
        /// </summary>
        public static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Common_Label_Close {
            get {
                return ResourceManager.GetString("Common_Label_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Common_Label_Enabled {
            get {
                return ResourceManager.GetString("Common_Label_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Common_Label_Error {
            get {
                return ResourceManager.GetString("Common_Label_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Common_Label_Open {
            get {
                return ResourceManager.GetString("Common_Label_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        public static string Common_Label_SaveAs {
            get {
                return ResourceManager.GetString("Common_Label_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X:.
        /// </summary>
        public static string Common_Label_X {
            get {
                return ResourceManager.GetString("Common_Label_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y:.
        /// </summary>
        public static string Common_Label_Y {
            get {
                return ResourceManager.GetString("Common_Label_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z:.
        /// </summary>
        public static string Common_Label_Z {
            get {
                return ResourceManager.GetString("Common_Label_Z", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTA Save Data Files (*.b)|*.b|All Files (*.*)|*.*.
        /// </summary>
        public static string FileFilter_Gta {
            get {
                return ResourceManager.GetString("FileFilter_Gta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ini Files (*.ini)|*.ini.
        /// </summary>
        public static string FileFilter_Ini {
            get {
                return ResourceManager.GetString("FileFilter_Ini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Files (*.log)|*.log|All Files (*.*)|*.*.
        /// </summary>
        public static string FileFilter_Log {
            get {
                return ResourceManager.GetString("FileFilter_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] GameData_PS2_Gxt_English {
            get {
                object obj = ResourceManager.GetObject("GameData_PS2_Gxt_English", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select....
        /// </summary>
        public static string General_ButtonText_Select {
            get {
                return ResourceManager.GetString("General_ButtonText_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheats used.
        /// </summary>
        public static string General_CheckBox_CheatsUsed {
            get {
                return ResourceManager.GetString("General_CheckBox_CheatsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative color palette.
        /// </summary>
        public static string General_CheckBox_EnhancedColors {
            get {
                return ResourceManager.GetString("General_CheckBox_EnhancedColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert look.
        /// </summary>
        public static string General_CheckBox_InvertLook {
            get {
                return ResourceManager.GetString("General_CheckBox_InvertLook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;BITE&apos; leaflets.
        /// </summary>
        public static string General_CheckBox_Leaflets {
            get {
                return ResourceManager.GetString("General_CheckBox_Leaflets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show HUD.
        /// </summary>
        public static string General_CheckBox_ShowHud {
            get {
                return ResourceManager.GetString("General_CheckBox_ShowHud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show subtitles.
        /// </summary>
        public static string General_CheckBox_ShowSubtitles {
            get {
                return ResourceManager.GetString("General_CheckBox_ShowSubtitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap analog and D-pad.
        /// </summary>
        public static string General_CheckBox_SwapAnalog {
            get {
                return ResourceManager.GetString("General_CheckBox_SwapAnalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxi boost jump.
        /// </summary>
        public static string General_CheckBox_TaxiBoost {
            get {
                return ResourceManager.GetString("General_CheckBox_TaxiBoost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vibration.
        /// </summary>
        public static string General_CheckBox_Vibration {
            get {
                return ResourceManager.GetString("General_CheckBox_Vibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widescreen.
        /// </summary>
        public static string General_CheckBox_Widescreen {
            get {
                return ResourceManager.GetString("General_CheckBox_Widescreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Settings.
        /// </summary>
        public static string General_GroupHeader_AudioSettings {
            get {
                return ResourceManager.GetString("General_GroupHeader_AudioSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness.
        /// </summary>
        public static string General_GroupHeader_Brightness {
            get {
                return ResourceManager.GetString("General_GroupHeader_Brightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls.
        /// </summary>
        public static string General_GroupHeader_Controls {
            get {
                return ResourceManager.GetString("General_GroupHeader_Controls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls Set.
        /// </summary>
        public static string General_GroupHeader_ControlsSet {
            get {
                return ResourceManager.GetString("General_GroupHeader_ControlsSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Time.
        /// </summary>
        public static string General_GroupHeader_CurrentTime {
            get {
                return ResourceManager.GetString("General_GroupHeader_CurrentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Settings.
        /// </summary>
        public static string General_GroupHeader_DisplaySettings {
            get {
                return ResourceManager.GetString("General_GroupHeader_DisplaySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Information.
        /// </summary>
        public static string General_GroupHeader_FileInfo {
            get {
                return ResourceManager.GetString("General_GroupHeader_FileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forced Weather.
        /// </summary>
        public static string General_GroupHeader_ForcedWeather {
            get {
                return ResourceManager.GetString("General_GroupHeader_ForcedWeather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In-Vehicle Camera.
        /// </summary>
        public static string General_GroupHeader_InVehicleCamera {
            get {
                return ResourceManager.GetString("General_GroupHeader_InVehicleCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Mission Passed Name.
        /// </summary>
        public static string General_GroupHeader_LastMissionPassed {
            get {
                return ResourceManager.GetString("General_GroupHeader_LastMissionPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Target.
        /// </summary>
        public static string General_GroupHeader_MapTarget {
            get {
                return ResourceManager.GetString("General_GroupHeader_MapTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute Duration.
        /// </summary>
        public static string General_GroupHeader_MinuteDuration {
            get {
                return ResourceManager.GetString("General_GroupHeader_MinuteDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous.
        /// </summary>
        public static string General_GroupHeader_Miscellaneous {
            get {
                return ResourceManager.GetString("General_GroupHeader_Miscellaneous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification Time.
        /// </summary>
        public static string General_GroupHeader_ModificationTime {
            get {
                return ResourceManager.GetString("General_GroupHeader_ModificationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On-Foot Camera.
        /// </summary>
        public static string General_GroupHeader_OnFootCamera {
            get {
                return ResourceManager.GetString("General_GroupHeader_OnFootCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radar Mode.
        /// </summary>
        public static string General_GroupHeader_RadarMode {
            get {
                return ResourceManager.GetString("General_GroupHeader_RadarMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio Volume.
        /// </summary>
        public static string General_GroupHeader_RadioVolume {
            get {
                return ResourceManager.GetString("General_GroupHeader_RadioVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SFX Volume.
        /// </summary>
        public static string General_GroupHeader_SfxVolume {
            get {
                return ResourceManager.GetString("General_GroupHeader_SfxVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string General_GroupHeader_Time {
            get {
                return ResourceManager.GetString("General_GroupHeader_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Time Played.
        /// </summary>
        public static string General_GroupHeader_TotalTimePlayed {
            get {
                return ResourceManager.GetString("General_GroupHeader_TotalTimePlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather.
        /// </summary>
        public static string General_GroupHeader_Weather {
            get {
                return ResourceManager.GetString("General_GroupHeader_Weather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness setting..
        /// </summary>
        public static string General_ToolTip_Brightness {
            get {
                return ResourceManager.GetString("General_ToolTip_Brightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates whether cheats have been used on this save..
        /// </summary>
        public static string General_ToolTip_CheatsUsed {
            get {
                return ResourceManager.GetString("General_ToolTip_CheatsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller configuration setting (PS2/PSP only)..
        /// </summary>
        public static string General_ToolTip_ControllerConfig {
            get {
                return ResourceManager.GetString("General_ToolTip_ControllerConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current time in-game..
        /// </summary>
        public static string General_ToolTip_CurrentTime {
            get {
                return ResourceManager.GetString("General_ToolTip_CurrentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activates an alternative color palette with an overall brighter look..
        /// </summary>
        public static string General_ToolTip_EnhancedColors {
            get {
                return ResourceManager.GetString("General_ToolTip_EnhancedColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force the weather to remain a certain way.
        ///Note that certain game events will override this setting..
        /// </summary>
        public static string General_ToolTip_ForcedWeather {
            get {
                return ResourceManager.GetString("General_ToolTip_ForcedWeather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In-vehicle camera setting..
        /// </summary>
        public static string General_ToolTip_InVehicleCamera {
            get {
                return ResourceManager.GetString("General_ToolTip_InVehicleCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables or disables look inversion..
        /// </summary>
        public static string General_ToolTip_InvertLook {
            get {
                return ResourceManager.GetString("General_ToolTip_InvertLook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the last mission passed (GXT string).
        ///On mobile saves, this will set the name of the file in the Load Game menu..
        /// </summary>
        public static string General_ToolTip_LastMissionPassed {
            get {
                return ResourceManager.GetString("General_ToolTip_LastMissionPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables or disables the Candy Suxxx &apos;BITE&apos; flyers from Vice City.
        ///When enabled, you will see the &apos;BITE&apos; leaflets appear as rubbish in the streets..
        /// </summary>
        public static string General_ToolTip_Leaflets {
            get {
                return ResourceManager.GetString("General_ToolTip_Leaflets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables or disables and sets the positon of the radar waypoint..
        /// </summary>
        public static string General_ToolTip_MapTarget {
            get {
                return ResourceManager.GetString("General_ToolTip_MapTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of real-world milliseconds that pass for each in-game minute..
        /// </summary>
        public static string General_ToolTip_MinuteDuration {
            get {
                return ResourceManager.GetString("General_ToolTip_MinuteDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The time when this file was last modified by the game (PS2 only)..
        /// </summary>
        public static string General_ToolTip_ModificationTime {
            get {
                return ResourceManager.GetString("General_ToolTip_ModificationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On-foot camera setting..
        /// </summary>
        public static string General_ToolTip_OnFootCamera {
            get {
                return ResourceManager.GetString("General_ToolTip_OnFootCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radar mode setting..
        /// </summary>
        public static string General_ToolTip_RadarMode {
            get {
                return ResourceManager.GetString("General_ToolTip_RadarMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio station volume..
        /// </summary>
        public static string General_ToolTip_RadioVolume {
            get {
                return ResourceManager.GetString("General_ToolTip_RadioVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound effects volume..
        /// </summary>
        public static string General_ToolTip_SfxVolume {
            get {
                return ResourceManager.GetString("General_ToolTip_SfxVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables or disables the HUD..
        /// </summary>
        public static string General_ToolTip_ShowHud {
            get {
                return ResourceManager.GetString("General_ToolTip_ShowHud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables or disables subtitles..
        /// </summary>
        public static string General_ToolTip_Subtitles {
            get {
                return ResourceManager.GetString("General_ToolTip_Subtitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swaps the functionality of the analog stick and directional buttons (PSP only)..
        /// </summary>
        public static string General_ToolTip_SwapAnalog {
            get {
                return ResourceManager.GetString("General_ToolTip_SwapAnalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables or disables the taxi hop feature found in Vice City and San Andreas.
        ///When enabled, press the horn while driving a taxi to make it hop!.
        /// </summary>
        public static string General_ToolTip_TaxiBoost {
            get {
                return ResourceManager.GetString("General_ToolTip_TaxiBoost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The total time spent playing the game.
        ///Format: days.hours:minutes:seconds..
        /// </summary>
        public static string General_ToolTip_TotalTimePlayed {
            get {
                return ResourceManager.GetString("General_ToolTip_TotalTimePlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables or disables vibration (PS2 only)..
        /// </summary>
        public static string General_ToolTip_Vibration {
            get {
                return ResourceManager.GetString("General_ToolTip_Vibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current weather conditions.
        ///The game uses a fixed set of weather patterns. At the top of every hour, the game will cycle to the next item in the list..
        /// </summary>
        public static string General_ToolTip_Weather {
            get {
                return ResourceManager.GetString("General_ToolTip_Weather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables or disables widesceen mode (PS2 only)..
        /// </summary>
        public static string General_ToolTip_Widescreen {
            get {
                return ResourceManager.GetString("General_ToolTip_Widescreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Log.
        /// </summary>
        public static string Log_DialogTitle_Save {
            get {
                return ResourceManager.GetString("Log_DialogTitle_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Log_Options_Clear {
            get {
                return ResourceManager.GetString("Log_Options_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Log_Options_Save {
            get {
                return ResourceManager.GetString("Log_Options_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save on exit.
        /// </summary>
        public static string Log_Options_SaveOnExit {
            get {
                return ResourceManager.GetString("Log_Options_SaveOnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the log when the application exits..
        /// </summary>
        public static string Log_ToolTip_SaveOnExit {
            get {
                return ResourceManager.GetString("Log_ToolTip_SaveOnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string Log_Window_Title {
            get {
                return ResourceManager.GetString("Log_Window_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unsaved changes. Are you sure you want to reload this file?.
        /// </summary>
        public static string Main_DialogText_ConfirmReload {
            get {
                return ResourceManager.GetString("Main_DialogText_ConfirmReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load file!.
        /// </summary>
        public static string Main_DialogText_FileLoadFail {
            get {
                return ResourceManager.GetString("Main_DialogText_FileLoadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save file!.
        /// </summary>
        public static string Main_DialogText_FileSaveFail {
            get {
                return ResourceManager.GetString("Main_DialogText_FileSaveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid GTA:LCS save data file.
        ///If you are trying to load a PSP save, make sure it is decrypted first..
        /// </summary>
        public static string Main_DialogText_InvalidGtaData {
            get {
                return ResourceManager.GetString("Main_DialogText_InvalidGtaData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save your changes?.
        /// </summary>
        public static string Main_DialogText_SaveBeforeClose {
            get {
                return ResourceManager.GetString("Main_DialogText_SaveBeforeClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fatal exception has occurred. The application will be terminated..
        /// </summary>
        public static string Main_DialogText_UnhandledException1 {
            get {
                return ResourceManager.GetString("Main_DialogText_UnhandledException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please report this error to {0} and attach the crash dump located at {1}..
        /// </summary>
        public static string Main_DialogText_UnhandledException2 {
            get {
                return ResourceManager.GetString("Main_DialogText_UnhandledException2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string Main_DialogTitle_ConfirmReload {
            get {
                return ResourceManager.GetString("Main_DialogTitle_ConfirmReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Failed.
        /// </summary>
        public static string Main_DialogTitle_FileLoadFail {
            get {
                return ResourceManager.GetString("Main_DialogTitle_FileLoadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Failed.
        /// </summary>
        public static string Main_DialogTitle_FileSaveFail {
            get {
                return ResourceManager.GetString("Main_DialogTitle_FileSaveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Save Data.
        /// </summary>
        public static string Main_DialogTitle_InvalidGtaData {
            get {
                return ResourceManager.GetString("Main_DialogTitle_InvalidGtaData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Main_DialogTitle_SaveBeforeClose {
            get {
                return ResourceManager.GetString("Main_DialogTitle_SaveBeforeClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled Exception.
        /// </summary>
        public static string Main_DialogTitle_UnhandledException {
            get {
                return ResourceManager.GetString("Main_DialogTitle_UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string Main_MenuFile {
            get {
                return ResourceManager.GetString("Main_MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close.
        /// </summary>
        public static string Main_MenuFile_Close {
            get {
                return ResourceManager.GetString("Main_MenuFile_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string Main_MenuFile_Exit {
            get {
                return ResourceManager.GetString("Main_MenuFile_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open....
        /// </summary>
        public static string Main_MenuFile_Open {
            get {
                return ResourceManager.GetString("Main_MenuFile_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Recent.
        /// </summary>
        public static string Main_MenuFile_OpenRecent {
            get {
                return ResourceManager.GetString("Main_MenuFile_OpenRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Reload/Revert.
        /// </summary>
        public static string Main_MenuFile_Reload {
            get {
                return ResourceManager.GetString("Main_MenuFile_Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        public static string Main_MenuFile_Save {
            get {
                return ResourceManager.GetString("Main_MenuFile_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save _As....
        /// </summary>
        public static string Main_MenuFile_SaveAs {
            get {
                return ResourceManager.GetString("Main_MenuFile_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se_ttings....
        /// </summary>
        public static string Main_MenuFile_Settings {
            get {
                return ResourceManager.GetString("Main_MenuFile_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string Main_MenuHelp {
            get {
                return ResourceManager.GetString("Main_MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About.
        /// </summary>
        public static string Main_MenuHelp_About {
            get {
                return ResourceManager.GetString("Main_MenuHelp_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for _Updates.
        /// </summary>
        public static string Main_MenuHelp_Update {
            get {
                return ResourceManager.GetString("Main_MenuHelp_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _View.
        /// </summary>
        public static string Main_MenuView {
            get {
                return ResourceManager.GetString("Main_MenuView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Advanced Options.
        /// </summary>
        public static string Main_MenuView_Advanced {
            get {
                return ResourceManager.GetString("Main_MenuView_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show _Log.
        /// </summary>
        public static string Main_MenuView_Log {
            get {
                return ResourceManager.GetString("Main_MenuView_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Main_Page_General {
            get {
                return ResourceManager.GetString("Main_Page_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Variables.
        /// </summary>
        public static string Main_Page_GlobalVariables {
            get {
                return ResourceManager.GetString("Main_Page_GlobalVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scripts.
        /// </summary>
        public static string Main_Page_Scripts {
            get {
                return ResourceManager.GetString("Main_Page_Scripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Main_Page_Start {
            get {
                return ResourceManager.GetString("Main_Page_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapons.
        /// </summary>
        public static string Main_Page_Weapons {
            get {
                return ResourceManager.GetString("Main_Page_Weapons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        public static string Main_StatusBar_FileModifiedFlag {
            get {
                return ResourceManager.GetString("Main_StatusBar_FileModifiedFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File closed..
        /// </summary>
        public static string Main_StatusText_FileClosed {
            get {
                return ResourceManager.GetString("Main_StatusText_FileClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load failed..
        /// </summary>
        public static string Main_StatusText_LoadFail {
            get {
                return ResourceManager.GetString("Main_StatusText_LoadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load successful..
        /// </summary>
        public static string Main_StatusText_LoadSuccess {
            get {
                return ResourceManager.GetString("Main_StatusText_LoadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload failed..
        /// </summary>
        public static string Main_StatusText_ReloadFail {
            get {
                return ResourceManager.GetString("Main_StatusText_ReloadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload successful..
        /// </summary>
        public static string Main_StatusText_ReloadSuccess {
            get {
                return ResourceManager.GetString("Main_StatusText_ReloadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save failed..
        /// </summary>
        public static string Main_StatusText_SaveFail {
            get {
                return ResourceManager.GetString("Main_StatusText_SaveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save succesful..
        /// </summary>
        public static string Main_StatusText_SaveSuccess {
            get {
                return ResourceManager.GetString("Main_StatusText_SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the GTA:LCS Save Editor!.
        /// </summary>
        public static string Main_StatusText_Welcome {
            get {
                return ResourceManager.GetString("Main_StatusText_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file is compatible with {0}..
        /// </summary>
        public static string Main_ToolTip_Compatibility {
            get {
                return ResourceManager.GetString("Main_ToolTip_Compatibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file has unsaved changes..
        /// </summary>
        public static string Main_ToolTip_UnsavedChanges {
            get {
                return ResourceManager.GetString("Main_ToolTip_UnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTA:LCS Save Editor.
        /// </summary>
        public static string Main_Window_Title {
            get {
                return ResourceManager.GetString("Main_Window_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Float.
        /// </summary>
        public static string Scripts_DataType_Float {
            get {
                return ResourceManager.GetString("Scripts_DataType_Float", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hex.
        /// </summary>
        public static string Scripts_DataType_Hex {
            get {
                return ResourceManager.GetString("Scripts_DataType_Hex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Int.
        /// </summary>
        public static string Scripts_DataType_Int {
            get {
                return ResourceManager.GetString("Scripts_DataType_Int", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load symbols file!.
        /// </summary>
        public static string Scripts_DialogText_SymbolsLoadFail {
            get {
                return ResourceManager.GetString("Scripts_DialogText_SymbolsLoadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save symbols file!.
        /// </summary>
        public static string Scripts_DialogText_SymbolsSaveFail {
            get {
                return ResourceManager.GetString("Scripts_DialogText_SymbolsSaveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Symbols File.
        /// </summary>
        public static string Scripts_DialogTitle_LoadSymbols {
            get {
                return ResourceManager.GetString("Scripts_DialogTitle_LoadSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Symbols File.
        /// </summary>
        public static string Scripts_DialogTitle_SaveSymbols {
            get {
                return ResourceManager.GetString("Scripts_DialogTitle_SaveSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Symbols Failed.
        /// </summary>
        public static string Scripts_DialogTitle_SymbolsLoadFail {
            get {
                return ResourceManager.GetString("Scripts_DialogTitle_SymbolsLoadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Symbols Failed.
        /// </summary>
        public static string Scripts_DialogTitle_SymbolsSaveFail {
            get {
                return ResourceManager.GetString("Scripts_DialogTitle_SymbolsSaveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Scripts_GlobalVariables_NameField {
            get {
                return ResourceManager.GetString("Scripts_GlobalVariables_NameField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Scripts_GlobalVariables_ValueField {
            get {
                return ResourceManager.GetString("Scripts_GlobalVariables_ValueField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActiveThreads.
        /// </summary>
        public static string Scripts_GroupHeader_ActiveThreads {
            get {
                return ResourceManager.GetString("Scripts_GroupHeader_ActiveThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Scripts_GroupHeader_DataType {
            get {
                return ResourceManager.GetString("Scripts_GroupHeader_DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Variables.
        /// </summary>
        public static string Scripts_GroupHeader_GlobalVariables {
            get {
                return ResourceManager.GetString("Scripts_GroupHeader_GlobalVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Scripts_GroupHeader_Options {
            get {
                return ResourceManager.GetString("Scripts_GroupHeader_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatible with the {0} version of GTA:LCS..
        /// </summary>
        public static string Scripts_Ini_Compatibility {
            get {
                return ResourceManager.GetString("Scripts_Ini_Compatibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated automatically by the GTA:LCS Save Editor..
        /// </summary>
        public static string Scripts_Ini_GeneratedBy {
            get {
                return ResourceManager.GetString("Scripts_Ini_GeneratedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Symbols....
        /// </summary>
        public static string Scripts_Options_LoadSymbols {
            get {
                return ResourceManager.GetString("Scripts_Options_LoadSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Symbols....
        /// </summary>
        public static string Scripts_Options_SaveSymbols {
            get {
                return ResourceManager.GetString("Scripts_Options_SaveSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Scripts_ThreadFlag_IsActive {
            get {
                return ResourceManager.GetString("Scripts_ThreadFlag_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission.
        /// </summary>
        public static string Scripts_ThreadFlag_IsMission {
            get {
                return ResourceManager.GetString("Scripts_ThreadFlag_IsMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W/B check enabled.
        /// </summary>
        public static string Scripts_ThreadFlag_IsWastedBustedCheckEnabled {
            get {
                return ResourceManager.GetString("Scripts_ThreadFlag_IsWastedBustedCheckEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission cleanup.
        /// </summary>
        public static string Scripts_ThreadFlag_UsesMissionCleanup {
            get {
                return ResourceManager.GetString("Scripts_ThreadFlag_UsesMissionCleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flags.
        /// </summary>
        public static string Scripts_ThreadProperties_Flags {
            get {
                return ResourceManager.GetString("Scripts_ThreadProperties_Flags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread ID.
        /// </summary>
        public static string Scripts_ThreadProperties_Id {
            get {
                return ResourceManager.GetString("Scripts_ThreadProperties_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruction Pointer.
        /// </summary>
        public static string Scripts_ThreadProperties_InstructionPointer {
            get {
                return ResourceManager.GetString("Scripts_ThreadProperties_InstructionPointer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Variables.
        /// </summary>
        public static string Scripts_ThreadProperties_LocalVariables {
            get {
                return ResourceManager.GetString("Scripts_ThreadProperties_LocalVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Scripts_ThreadProperties_Name {
            get {
                return ResourceManager.GetString("Scripts_ThreadProperties_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gosub Return Stack.
        /// </summary>
        public static string Scripts_ThreadProperties_ReturnStack {
            get {
                return ResourceManager.GetString("Scripts_ThreadProperties_ReturnStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gosub Depth.
        /// </summary>
        public static string Scripts_ThreadProperties_ReturnStackTop {
            get {
                return ResourceManager.GetString("Scripts_ThreadProperties_ReturnStackTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer 1:.
        /// </summary>
        public static string Scripts_ThreadProperties_Timer1 {
            get {
                return ResourceManager.GetString("Scripts_ThreadProperties_Timer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer 2:.
        /// </summary>
        public static string Scripts_ThreadProperties_Timer2 {
            get {
                return ResourceManager.GetString("Scripts_ThreadProperties_Timer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timers.
        /// </summary>
        public static string Scripts_ThreadProperties_Timers {
            get {
                return ResourceManager.GetString("Scripts_ThreadProperties_Timers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wake Time:.
        /// </summary>
        public static string Scripts_ThreadProperties_WakeTime {
            get {
                return ResourceManager.GetString("Scripts_ThreadProperties_WakeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assault.
        /// </summary>
        public static string Weapons_Slot_Assault {
            get {
                return ResourceManager.GetString("Weapons_Slot_Assault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hand.
        /// </summary>
        public static string Weapons_Slot_Hand {
            get {
                return ResourceManager.GetString("Weapons_Slot_Hand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy.
        /// </summary>
        public static string Weapons_Slot_Heavy {
            get {
                return ResourceManager.GetString("Weapons_Slot_Heavy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melee.
        /// </summary>
        public static string Weapons_Slot_Melee {
            get {
                return ResourceManager.GetString("Weapons_Slot_Melee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pistol.
        /// </summary>
        public static string Weapons_Slot_Pistol {
            get {
                return ResourceManager.GetString("Weapons_Slot_Pistol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projectile.
        /// </summary>
        public static string Weapons_Slot_Projectile {
            get {
                return ResourceManager.GetString("Weapons_Slot_Projectile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shotgun.
        /// </summary>
        public static string Weapons_Slot_Shotgun {
            get {
                return ResourceManager.GetString("Weapons_Slot_Shotgun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMG.
        /// </summary>
        public static string Weapons_Slot_Smg {
            get {
                return ResourceManager.GetString("Weapons_Slot_Smg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sniper.
        /// </summary>
        public static string Weapons_Slot_Sniper {
            get {
                return ResourceManager.GetString("Weapons_Slot_Sniper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special.
        /// </summary>
        public static string Weapons_Slot_Special {
            get {
                return ResourceManager.GetString("Weapons_Slot_Special", resourceCulture);
            }
        }
    }
}
