//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LcsSaveEditor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FrontendResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FrontendResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LcsSaveEditor.Resources.FrontendResources", typeof(FrontendResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About_Window_Title {
            get {
                return ResourceManager.GetString("About_Window_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thehambone.
        /// </summary>
        public static string App_Author {
            get {
                return ResourceManager.GetString("App_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wes Hampson.
        /// </summary>
        public static string App_AuthorAlternate {
            get {
                return ResourceManager.GetString("App_AuthorAlternate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thehambone93@gmail.com.
        /// </summary>
        public static string App_AuthorContact {
            get {
                return ResourceManager.GetString("App_AuthorContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (C) 2016-2019 Wes Hampson. All Rights Reserved..
        /// </summary>
        public static string App_Copyright {
            get {
                return ResourceManager.GetString("App_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand Theft Auto: Liberty City Stories savegame editor..
        /// </summary>
        public static string App_Description {
            get {
                return ResourceManager.GetString("App_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host OS: {0}.
        /// </summary>
        public static string App_HostOS {
            get {
                return ResourceManager.GetString("App_HostOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTA:LCS Save Editor.
        /// </summary>
        public static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0} (build {1}).
        /// </summary>
        public static string App_Version {
            get {
                return ResourceManager.GetString("App_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Common_Close {
            get {
                return ResourceManager.GetString("Common_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Common_Error {
            get {
                return ResourceManager.GetString("Common_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Common_Open {
            get {
                return ResourceManager.GetString("Common_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        public static string Common_SaveAs {
            get {
                return ResourceManager.GetString("Common_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTA Save Data Files (*.b)|*.b|All Files (*.*)|*.*.
        /// </summary>
        public static string FileFilter_Gta {
            get {
                return ResourceManager.GetString("FileFilter_Gta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ini Files (*.ini)|*.ini.
        /// </summary>
        public static string FileFilter_Ini {
            get {
                return ResourceManager.GetString("FileFilter_Ini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Files (*.log)|*.log|All Files (*.*)|*.*.
        /// </summary>
        public static string FileFilter_Log {
            get {
                return ResourceManager.GetString("FileFilter_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string GlobalVariables_ContextMenu_Delete {
            get {
                return ResourceManager.GetString("GlobalVariables_ContextMenu_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Above.
        /// </summary>
        public static string GlobalVariables_ContextMenu_InsertAbove {
            get {
                return ResourceManager.GetString("GlobalVariables_ContextMenu_InsertAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Below.
        /// </summary>
        public static string GlobalVariables_ContextMenu_InsertBelow {
            get {
                return ResourceManager.GetString("GlobalVariables_ContextMenu_InsertBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True/False.
        /// </summary>
        public static string GlobalVariables_DataType_Bool {
            get {
                return ResourceManager.GetString("GlobalVariables_DataType_Bool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Float.
        /// </summary>
        public static string GlobalVariables_DataType_Float {
            get {
                return ResourceManager.GetString("GlobalVariables_DataType_Float", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Int32.
        /// </summary>
        public static string GlobalVariables_DataType_Int32 {
            get {
                return ResourceManager.GetString("GlobalVariables_DataType_Int32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string GlobalVariables_DataType_Name {
            get {
                return ResourceManager.GetString("GlobalVariables_DataType_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UInt32.
        /// </summary>
        public static string GlobalVariables_DataType_UInt32 {
            get {
                return ResourceManager.GetString("GlobalVariables_DataType_UInt32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load symbols file!.
        /// </summary>
        public static string GlobalVariables_DialogText_SymbolsLoadFail {
            get {
                return ResourceManager.GetString("GlobalVariables_DialogText_SymbolsLoadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save symbols file!.
        /// </summary>
        public static string GlobalVariables_DialogText_SymbolsSaveFail {
            get {
                return ResourceManager.GetString("GlobalVariables_DialogText_SymbolsSaveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Symbols File.
        /// </summary>
        public static string GlobalVariables_DialogTitle_LoadSymbols {
            get {
                return ResourceManager.GetString("GlobalVariables_DialogTitle_LoadSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Symbols File.
        /// </summary>
        public static string GlobalVariables_DialogTitle_SaveSymbols {
            get {
                return ResourceManager.GetString("GlobalVariables_DialogTitle_SaveSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Symbols Failed.
        /// </summary>
        public static string GlobalVariables_DialogTitle_SymbolsLoadFail {
            get {
                return ResourceManager.GetString("GlobalVariables_DialogTitle_SymbolsLoadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Symbols Failed.
        /// </summary>
        public static string GlobalVariables_DialogTitle_SymbolsSaveFail {
            get {
                return ResourceManager.GetString("GlobalVariables_DialogTitle_SymbolsSaveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatible with the {0} version of GTA:LCS..
        /// </summary>
        public static string GlobalVariables_Ini_Compatibility {
            get {
                return ResourceManager.GetString("GlobalVariables_Ini_Compatibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated automatically by the GTA:LCS Save Editor..
        /// </summary>
        public static string GlobalVariables_Ini_GeneratedBy {
            get {
                return ResourceManager.GetString("GlobalVariables_Ini_GeneratedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Symbols....
        /// </summary>
        public static string GlobalVariables_Options_LoadSymbols {
            get {
                return ResourceManager.GetString("GlobalVariables_Options_LoadSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Symbols....
        /// </summary>
        public static string GlobalVariables_Options_SaveSymbols {
            get {
                return ResourceManager.GetString("GlobalVariables_Options_SaveSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Log.
        /// </summary>
        public static string Log_DialogTitle_Save {
            get {
                return ResourceManager.GetString("Log_DialogTitle_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Log_Options_Clear {
            get {
                return ResourceManager.GetString("Log_Options_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Log_Options_Save {
            get {
                return ResourceManager.GetString("Log_Options_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save on exit.
        /// </summary>
        public static string Log_Options_SaveOnExit {
            get {
                return ResourceManager.GetString("Log_Options_SaveOnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the log when the application exits..
        /// </summary>
        public static string Log_ToolTip_SaveOnExit {
            get {
                return ResourceManager.GetString("Log_ToolTip_SaveOnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string Log_Window_Title {
            get {
                return ResourceManager.GetString("Log_Window_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unsaved changes. Are you sure you want to reload this file?.
        /// </summary>
        public static string Main_DialogText_ConfirmReload {
            get {
                return ResourceManager.GetString("Main_DialogText_ConfirmReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load file!.
        /// </summary>
        public static string Main_DialogText_FileLoadFail {
            get {
                return ResourceManager.GetString("Main_DialogText_FileLoadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save file!.
        /// </summary>
        public static string Main_DialogText_FileSaveFail {
            get {
                return ResourceManager.GetString("Main_DialogText_FileSaveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid GTA:LCS save data file.
        ///If you are trying to load a PSP save, make sure it is decrypted first..
        /// </summary>
        public static string Main_DialogText_InvalidGtaData {
            get {
                return ResourceManager.GetString("Main_DialogText_InvalidGtaData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save your changes?.
        /// </summary>
        public static string Main_DialogText_SaveBeforeClose {
            get {
                return ResourceManager.GetString("Main_DialogText_SaveBeforeClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fatal exception has occurred. The application will be terminated..
        /// </summary>
        public static string Main_DialogText_UnhandledException1 {
            get {
                return ResourceManager.GetString("Main_DialogText_UnhandledException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please report this error to {0} and attach the crash dump located at {1}..
        /// </summary>
        public static string Main_DialogText_UnhandledException2 {
            get {
                return ResourceManager.GetString("Main_DialogText_UnhandledException2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string Main_DialogTitle_ConfirmReload {
            get {
                return ResourceManager.GetString("Main_DialogTitle_ConfirmReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Failed.
        /// </summary>
        public static string Main_DialogTitle_FileLoadFail {
            get {
                return ResourceManager.GetString("Main_DialogTitle_FileLoadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Failed.
        /// </summary>
        public static string Main_DialogTitle_FileSaveFail {
            get {
                return ResourceManager.GetString("Main_DialogTitle_FileSaveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Save Data.
        /// </summary>
        public static string Main_DialogTitle_InvalidGtaData {
            get {
                return ResourceManager.GetString("Main_DialogTitle_InvalidGtaData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Main_DialogTitle_SaveBeforeClose {
            get {
                return ResourceManager.GetString("Main_DialogTitle_SaveBeforeClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled Exception.
        /// </summary>
        public static string Main_DialogTitle_UnhandledException {
            get {
                return ResourceManager.GetString("Main_DialogTitle_UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string Main_MenuFile {
            get {
                return ResourceManager.GetString("Main_MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close.
        /// </summary>
        public static string Main_MenuFile_Close {
            get {
                return ResourceManager.GetString("Main_MenuFile_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string Main_MenuFile_Exit {
            get {
                return ResourceManager.GetString("Main_MenuFile_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open....
        /// </summary>
        public static string Main_MenuFile_Open {
            get {
                return ResourceManager.GetString("Main_MenuFile_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Recent.
        /// </summary>
        public static string Main_MenuFile_OpenRecent {
            get {
                return ResourceManager.GetString("Main_MenuFile_OpenRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Reload/Revert.
        /// </summary>
        public static string Main_MenuFile_Reload {
            get {
                return ResourceManager.GetString("Main_MenuFile_Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        public static string Main_MenuFile_Save {
            get {
                return ResourceManager.GetString("Main_MenuFile_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save _As....
        /// </summary>
        public static string Main_MenuFile_SaveAs {
            get {
                return ResourceManager.GetString("Main_MenuFile_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se_ttings....
        /// </summary>
        public static string Main_MenuFile_Settings {
            get {
                return ResourceManager.GetString("Main_MenuFile_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string Main_MenuHelp {
            get {
                return ResourceManager.GetString("Main_MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About.
        /// </summary>
        public static string Main_MenuHelp_About {
            get {
                return ResourceManager.GetString("Main_MenuHelp_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for _Updates.
        /// </summary>
        public static string Main_MenuHelp_Update {
            get {
                return ResourceManager.GetString("Main_MenuHelp_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _View.
        /// </summary>
        public static string Main_MenuView {
            get {
                return ResourceManager.GetString("Main_MenuView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Advanced Options.
        /// </summary>
        public static string Main_MenuView_Advanced {
            get {
                return ResourceManager.GetString("Main_MenuView_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show _Log.
        /// </summary>
        public static string Main_MenuView_Log {
            get {
                return ResourceManager.GetString("Main_MenuView_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GlobalVariables.
        /// </summary>
        public static string Main_Page_GlobalVariables {
            get {
                return ResourceManager.GetString("Main_Page_GlobalVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Main_Page_Start {
            get {
                return ResourceManager.GetString("Main_Page_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapons.
        /// </summary>
        public static string Main_Page_Weapons {
            get {
                return ResourceManager.GetString("Main_Page_Weapons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        public static string Main_StatusBar_FileModifiedFlag {
            get {
                return ResourceManager.GetString("Main_StatusBar_FileModifiedFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File closed..
        /// </summary>
        public static string Main_StatusText_FileClosed {
            get {
                return ResourceManager.GetString("Main_StatusText_FileClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load failed..
        /// </summary>
        public static string Main_StatusText_LoadFail {
            get {
                return ResourceManager.GetString("Main_StatusText_LoadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load successful..
        /// </summary>
        public static string Main_StatusText_LoadSuccess {
            get {
                return ResourceManager.GetString("Main_StatusText_LoadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload failed..
        /// </summary>
        public static string Main_StatusText_ReloadFail {
            get {
                return ResourceManager.GetString("Main_StatusText_ReloadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload successful..
        /// </summary>
        public static string Main_StatusText_ReloadSuccess {
            get {
                return ResourceManager.GetString("Main_StatusText_ReloadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save failed..
        /// </summary>
        public static string Main_StatusText_SaveFail {
            get {
                return ResourceManager.GetString("Main_StatusText_SaveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save succesful..
        /// </summary>
        public static string Main_StatusText_SaveSuccess {
            get {
                return ResourceManager.GetString("Main_StatusText_SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the GTA:LCS Save Editor!.
        /// </summary>
        public static string Main_StatusText_Welcome {
            get {
                return ResourceManager.GetString("Main_StatusText_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file is compatible with {0}..
        /// </summary>
        public static string Main_ToolTip_Compatibility {
            get {
                return ResourceManager.GetString("Main_ToolTip_Compatibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file has unsaved changes..
        /// </summary>
        public static string Main_ToolTip_UnsavedChanges {
            get {
                return ResourceManager.GetString("Main_ToolTip_UnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTA:LCS Save Editor.
        /// </summary>
        public static string Main_Window_Title {
            get {
                return ResourceManager.GetString("Main_Window_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assault.
        /// </summary>
        public static string Weapons_Slot_Assault {
            get {
                return ResourceManager.GetString("Weapons_Slot_Assault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hand.
        /// </summary>
        public static string Weapons_Slot_Hand {
            get {
                return ResourceManager.GetString("Weapons_Slot_Hand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy.
        /// </summary>
        public static string Weapons_Slot_Heavy {
            get {
                return ResourceManager.GetString("Weapons_Slot_Heavy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melee.
        /// </summary>
        public static string Weapons_Slot_Melee {
            get {
                return ResourceManager.GetString("Weapons_Slot_Melee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pistol.
        /// </summary>
        public static string Weapons_Slot_Pistol {
            get {
                return ResourceManager.GetString("Weapons_Slot_Pistol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projectile.
        /// </summary>
        public static string Weapons_Slot_Projectile {
            get {
                return ResourceManager.GetString("Weapons_Slot_Projectile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shotgun.
        /// </summary>
        public static string Weapons_Slot_Shotgun {
            get {
                return ResourceManager.GetString("Weapons_Slot_Shotgun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMG.
        /// </summary>
        public static string Weapons_Slot_Smg {
            get {
                return ResourceManager.GetString("Weapons_Slot_Smg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sniper.
        /// </summary>
        public static string Weapons_Slot_Sniper {
            get {
                return ResourceManager.GetString("Weapons_Slot_Sniper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special.
        /// </summary>
        public static string Weapons_Slot_Special {
            get {
                return ResourceManager.GetString("Weapons_Slot_Special", resourceCulture);
            }
        }
    }
}
