//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LcsSaveEditor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LcsSaveEditor.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thehambone.
        /// </summary>
        public static string AppAuthor {
            get {
                return ResourceManager.GetString("AppAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wes Hampson.
        /// </summary>
        public static string AppAuthorAlternate {
            get {
                return ResourceManager.GetString("AppAuthorAlternate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thehambone93@gmail.com.
        /// </summary>
        public static string AppAuthorContact {
            get {
                return ResourceManager.GetString("AppAuthorContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (C) 2016-2019 Wes Hampson. All Rights Reserved..
        /// </summary>
        public static string AppCopyright {
            get {
                return ResourceManager.GetString("AppCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand Theft Auto: Liberty City Stories savegame editor..
        /// </summary>
        public static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A graphical tool for editing Grand Theft Auto: Liberty City Stories savedata files..
        /// </summary>
        public static string AppDescriptionLong {
            get {
                return ResourceManager.GetString("AppDescriptionLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTA:LCS Save Editor.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save your changes?.
        /// </summary>
        public static string DialogTextFileSavePrompt {
            get {
                return ResourceManager.GetString("DialogTextFileSavePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fatal exception has occurred. The application will be terminated..
        /// </summary>
        public static string DialogTextUnhandledException1 {
            get {
                return ResourceManager.GetString("DialogTextUnhandledException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact {0} about this error..
        /// </summary>
        public static string DialogTextUnhandledException2 {
            get {
                return ResourceManager.GetString("DialogTextUnhandledException2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes?.
        /// </summary>
        public static string DialogTitleFileSavePrompt {
            get {
                return ResourceManager.GetString("DialogTitleFileSavePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string DialogTitleGeneralError {
            get {
                return ResourceManager.GetString("DialogTitleGeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled Exception.
        /// </summary>
        public static string DialogTitleUnhandledException {
            get {
                return ResourceManager.GetString("DialogTitleUnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConvertBack is not supported for this converter..
        /// </summary>
        public static string ExceptionTextConvertBackNotSupported {
            get {
                return ResourceManager.GetString("ExceptionTextConvertBackNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The block size in the header does not match the number of available bytes in the stream..
        /// </summary>
        public static string ExceptionTextIncorrectBlockSize {
            get {
                return ResourceManager.GetString("ExceptionTextIncorrectBlockSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect block tag - &apos;{0}&apos;. Expected &apos;{1}&apos;..
        /// </summary>
        public static string ExceptionTextInvalidBlockTag {
            get {
                return ResourceManager.GetString("ExceptionTextInvalidBlockTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid GTA:LCS savedata file.
        ///If you are trying to load a PSP save, you may have to decrypt it first..
        /// </summary>
        public static string ExceptionTextInvalidSaveData {
            get {
                return ResourceManager.GetString("ExceptionTextInvalidSaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple calls to this function are not supported..
        /// </summary>
        public static string ExceptionTextMultipleCallsNotSupported {
            get {
                return ResourceManager.GetString("ExceptionTextMultipleCallsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You weren&apos;t supposed to be able to get here, you know..
        /// </summary>
        public static string ExceptionTextOops {
            get {
                return ResourceManager.GetString("ExceptionTextOops", resourceCulture);
            }
        }
    }
}
