//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LcsSaveEditor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LcsSaveEditor.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thehambone.
        /// </summary>
        public static string AppAuthor {
            get {
                return ResourceManager.GetString("AppAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wes Hampson.
        /// </summary>
        public static string AppAuthorAlternate {
            get {
                return ResourceManager.GetString("AppAuthorAlternate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thehambone93@gmail.com.
        /// </summary>
        public static string AppAuthorContact {
            get {
                return ResourceManager.GetString("AppAuthorContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (C) 2016-2019 Wes Hampson. All Rights Reserved..
        /// </summary>
        public static string AppCopyright {
            get {
                return ResourceManager.GetString("AppCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand Theft Auto: Liberty City Stories savegame editor..
        /// </summary>
        public static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A graphical tool for editing Grand Theft Auto: Liberty City Stories savedata files..
        /// </summary>
        public static string AppDescriptionLong {
            get {
                return ResourceManager.GetString("AppDescriptionLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTA:LCS Save Editor.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save your changes?.
        /// </summary>
        public static string DialogTextSaveChangesPrompt {
            get {
                return ResourceManager.GetString("DialogTextSaveChangesPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fatal exception has occurred. The application will be terminated..
        /// </summary>
        public static string DialogTextUnhandledException1 {
            get {
                return ResourceManager.GetString("DialogTextUnhandledException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact {0} about this error..
        /// </summary>
        public static string DialogTextUnhandledException2 {
            get {
                return ResourceManager.GetString("DialogTextUnhandledException2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string DialogTitleAbout {
            get {
                return ResourceManager.GetString("DialogTitleAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string DialogTitleError {
            get {
                return ResourceManager.GetString("DialogTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open....
        /// </summary>
        public static string DialogTitleOpenFile {
            get {
                return ResourceManager.GetString("DialogTitleOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes?.
        /// </summary>
        public static string DialogTitleSaveChangesPrompt {
            get {
                return ResourceManager.GetString("DialogTitleSaveChangesPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As....
        /// </summary>
        public static string DialogTitleSaveFileAs {
            get {
                return ResourceManager.GetString("DialogTitleSaveFileAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled Exception.
        /// </summary>
        public static string DialogTitleUnhandledException {
            get {
                return ResourceManager.GetString("DialogTitleUnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConvertBack is not supported for this converter..
        /// </summary>
        public static string ExceptionTextConvertBackNotSupported {
            get {
                return ResourceManager.GetString("ExceptionTextConvertBackNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The block size in the header does not match the number of available bytes in the stream..
        /// </summary>
        public static string ExceptionTextIncorrectBlockSize {
            get {
                return ResourceManager.GetString("ExceptionTextIncorrectBlockSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect block tag - &apos;{0}&apos;. Expected &apos;{1}&apos;..
        /// </summary>
        public static string ExceptionTextInvalidBlockTag {
            get {
                return ResourceManager.GetString("ExceptionTextInvalidBlockTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid GTA:LCS savedata file.
        ///If you are trying to load a PSP save, you may have to decrypt it first..
        /// </summary>
        public static string ExceptionTextInvalidSaveData {
            get {
                return ResourceManager.GetString("ExceptionTextInvalidSaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received PropertyChanged notification from item not in collection..
        /// </summary>
        public static string ExceptionTextItemPropertyChanged {
            get {
                return ResourceManager.GetString("ExceptionTextItemPropertyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple calls to this function are not supported..
        /// </summary>
        public static string ExceptionTextMultipleCallsNotSupported {
            get {
                return ResourceManager.GetString("ExceptionTextMultipleCallsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You weren&apos;t supposed to be able to get here, you know..
        /// </summary>
        public static string ExceptionTextOops {
            get {
                return ResourceManager.GetString("ExceptionTextOops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTA:LCS Save Data (*.b)|*.b|All Files (*.*)|*.*.
        /// </summary>
        public static string FileFilterSaveData {
            get {
                return ResourceManager.GetString("FileFilterSaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        public static string FlagFileModified {
            get {
                return ResourceManager.GetString("FlagFileModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string MenuHeaderFile {
            get {
                return ResourceManager.GetString("MenuHeaderFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string MenuHeaderHelp {
            get {
                return ResourceManager.GetString("MenuHeaderHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MenuItemHeaderAbout {
            get {
                return ResourceManager.GetString("MenuItemHeaderAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close.
        /// </summary>
        public static string MenuItemHeaderClose {
            get {
                return ResourceManager.GetString("MenuItemHeaderClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string MenuItemHeaderExit {
            get {
                return ResourceManager.GetString("MenuItemHeaderExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open....
        /// </summary>
        public static string MenuItemHeaderOpen {
            get {
                return ResourceManager.GetString("MenuItemHeaderOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        public static string MenuItemHeaderSave {
            get {
                return ResourceManager.GetString("MenuItemHeaderSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save _As....
        /// </summary>
        public static string MenuItemHeaderSaveAs {
            get {
                return ResourceManager.GetString("MenuItemHeaderSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapons.
        /// </summary>
        public static string PageHeaderWeapons {
            get {
                return ResourceManager.GetString("PageHeaderWeapons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file loaded..
        /// </summary>
        public static string StatusTextFileNotLoaded {
            get {
                return ResourceManager.GetString("StatusTextFileNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load failed!.
        /// </summary>
        public static string StatusTextFileOpenFail {
            get {
                return ResourceManager.GetString("StatusTextFileOpenFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load successful..
        /// </summary>
        public static string StatusTextFileOpenSuccess {
            get {
                return ResourceManager.GetString("StatusTextFileOpenSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save failed!.
        /// </summary>
        public static string StatusTextFileSaveFailed {
            get {
                return ResourceManager.GetString("StatusTextFileSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save successful..
        /// </summary>
        public static string StatusTextFileSaveSuccess {
            get {
                return ResourceManager.GetString("StatusTextFileSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the GTA:LCS Save Editor!.
        /// </summary>
        public static string StatusTextWelcome {
            get {
                return ResourceManager.GetString("StatusTextWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file has unsaved changes..
        /// </summary>
        public static string ToolTipTextFileModified {
            get {
                return ResourceManager.GetString("ToolTipTextFileModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a {0}-compatible save..
        /// </summary>
        public static string ToolTipTextFileType1 {
            get {
                return ResourceManager.GetString("ToolTipTextFileType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an {0}-compatible save..
        /// </summary>
        public static string ToolTipTextFileType2 {
            get {
                return ResourceManager.GetString("ToolTipTextFileType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assault.
        /// </summary>
        public static string WeaponSlotAssault {
            get {
                return ResourceManager.GetString("WeaponSlotAssault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hand.
        /// </summary>
        public static string WeaponSlotHand {
            get {
                return ResourceManager.GetString("WeaponSlotHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy.
        /// </summary>
        public static string WeaponSlotHeavy {
            get {
                return ResourceManager.GetString("WeaponSlotHeavy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melee.
        /// </summary>
        public static string WeaponSlotMelee {
            get {
                return ResourceManager.GetString("WeaponSlotMelee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pistol.
        /// </summary>
        public static string WeaponSlotPistol {
            get {
                return ResourceManager.GetString("WeaponSlotPistol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projectile.
        /// </summary>
        public static string WeaponSlotProjectile {
            get {
                return ResourceManager.GetString("WeaponSlotProjectile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shotgun.
        /// </summary>
        public static string WeaponSlotShotgun {
            get {
                return ResourceManager.GetString("WeaponSlotShotgun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMG.
        /// </summary>
        public static string WeaponSlotSmg {
            get {
                return ResourceManager.GetString("WeaponSlotSmg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sniper.
        /// </summary>
        public static string WeaponSlotSniper {
            get {
                return ResourceManager.GetString("WeaponSlotSniper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special.
        /// </summary>
        public static string WeaponSlotSpecial {
            get {
                return ResourceManager.GetString("WeaponSlotSpecial", resourceCulture);
            }
        }
    }
}
