//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LcsSaveEditor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LcsSaveEditor.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thehambone.
        /// </summary>
        public static string AppAuthor {
            get {
                return ResourceManager.GetString("AppAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wes Hampson.
        /// </summary>
        public static string AppAuthorAlternate {
            get {
                return ResourceManager.GetString("AppAuthorAlternate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thehambone93@gmail.com.
        /// </summary>
        public static string AppAuthorContact {
            get {
                return ResourceManager.GetString("AppAuthorContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (C) 2016-2019 Wes Hampson. All Rights Reserved..
        /// </summary>
        public static string AppCopyright {
            get {
                return ResourceManager.GetString("AppCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand Theft Auto: Liberty City Stories savegame editor..
        /// </summary>
        public static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A graphical tool for editing Grand Theft Auto: Liberty City Stories savedata files..
        /// </summary>
        public static string AppDescriptionLong {
            get {
                return ResourceManager.GetString("AppDescriptionLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTA:LCS Save Editor.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string ButtonTextClear {
            get {
                return ResourceManager.GetString("ButtonTextClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ButtonTextClose {
            get {
                return ResourceManager.GetString("ButtonTextClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Symbols....
        /// </summary>
        public static string ButtonTextLoadSymbols {
            get {
                return ResourceManager.GetString("ButtonTextLoadSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save....
        /// </summary>
        public static string ButtonTextSave {
            get {
                return ResourceManager.GetString("ButtonTextSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Symbols....
        /// </summary>
        public static string ButtonTextSaveSymbols {
            get {
                return ResourceManager.GetString("ButtonTextSaveSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatible with the {0} version of GTA:LCS..
        /// </summary>
        public static string CustomVariablesCompatibilityText {
            get {
                return ResourceManager.GetString("CustomVariablesCompatibilityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated automatically by the GTA:LCS Save Editor..
        /// </summary>
        public static string CustomVariablesGeneratedByText {
            get {
                return ResourceManager.GetString("CustomVariablesGeneratedByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save your changes?.
        /// </summary>
        public static string DialogTextSaveChangesPrompt {
            get {
                return ResourceManager.GetString("DialogTextSaveChangesPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fatal exception has occurred. The application will be terminated..
        /// </summary>
        public static string DialogTextUnhandledException1 {
            get {
                return ResourceManager.GetString("DialogTextUnhandledException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please report this error to {0} and attach the crash dump located at {1}..
        /// </summary>
        public static string DialogTextUnhandledException2 {
            get {
                return ResourceManager.GetString("DialogTextUnhandledException2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string DialogTitleAbout {
            get {
                return ResourceManager.GetString("DialogTitleAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string DialogTitleError {
            get {
                return ResourceManager.GetString("DialogTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open....
        /// </summary>
        public static string DialogTitleOpenFile {
            get {
                return ResourceManager.GetString("DialogTitleOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes?.
        /// </summary>
        public static string DialogTitleSaveChangesPrompt {
            get {
                return ResourceManager.GetString("DialogTitleSaveChangesPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As....
        /// </summary>
        public static string DialogTitleSaveFileAs {
            get {
                return ResourceManager.GetString("DialogTitleSaveFileAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled Exception.
        /// </summary>
        public static string DialogTitleUnhandledException {
            get {
                return ResourceManager.GetString("DialogTitleUnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConvertBack is not supported for this converter..
        /// </summary>
        public static string ExceptionConvertBackNotSupported {
            get {
                return ResourceManager.GetString("ExceptionConvertBackNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The block size in the header does not match the number of available bytes in the stream..
        /// </summary>
        public static string ExceptionIncorrectBlockSize {
            get {
                return ResourceManager.GetString("ExceptionIncorrectBlockSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect block tag - &apos;{0}&apos;. Expected &apos;{1}&apos;..
        /// </summary>
        public static string ExceptionInvalidBlockTag {
            get {
                return ResourceManager.GetString("ExceptionInvalidBlockTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received PropertyChanged notification from item not in collection..
        /// </summary>
        public static string ExceptionInvalidItemPropertyChanged {
            get {
                return ResourceManager.GetString("ExceptionInvalidItemPropertyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid GTA:LCS savedata file.
        ///If you are trying to load a PSP save, you may have to decrypt it first..
        /// </summary>
        public static string ExceptionInvalidSaveData {
            get {
                return ResourceManager.GetString("ExceptionInvalidSaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple calls to this function are not supported..
        /// </summary>
        public static string ExceptionMultipleCallsNotSupported {
            get {
                return ResourceManager.GetString("ExceptionMultipleCallsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You weren&apos;t supposed to be able to get here, you know..
        /// </summary>
        public static string ExceptionOops {
            get {
                return ResourceManager.GetString("ExceptionOops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is a static array; it cannot be resized..
        /// </summary>
        public static string ExceptionStaticArray {
            get {
                return ResourceManager.GetString("ExceptionStaticArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string FieldName {
            get {
                return ResourceManager.GetString("FieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True/False.
        /// </summary>
        public static string FieldValueBoolean {
            get {
                return ResourceManager.GetString("FieldValueBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Float.
        /// </summary>
        public static string FieldValueFloat {
            get {
                return ResourceManager.GetString("FieldValueFloat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Int32.
        /// </summary>
        public static string FieldValueInt32 {
            get {
                return ResourceManager.GetString("FieldValueInt32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UInt32.
        /// </summary>
        public static string FieldValueUInt32 {
            get {
                return ResourceManager.GetString("FieldValueUInt32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ini Files (*.ini)|*.ini.
        /// </summary>
        public static string FileFilterIni {
            get {
                return ResourceManager.GetString("FileFilterIni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Files (*.log)|*.log|All Files (*.*)|*.*.
        /// </summary>
        public static string FileFilterLog {
            get {
                return ResourceManager.GetString("FileFilterLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTA Save Data Files (*.b)|*.b|All Files (*.*)|*.*.
        /// </summary>
        public static string FileFilterSaveData {
            get {
                return ResourceManager.GetString("FileFilterSaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        public static string FlagFileModified {
            get {
                return ResourceManager.GetString("FlagFileModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string MenuHeaderFile {
            get {
                return ResourceManager.GetString("MenuHeaderFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string MenuHeaderHelp {
            get {
                return ResourceManager.GetString("MenuHeaderHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MenuItemHeaderAbout {
            get {
                return ResourceManager.GetString("MenuItemHeaderAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close.
        /// </summary>
        public static string MenuItemHeaderClose {
            get {
                return ResourceManager.GetString("MenuItemHeaderClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string MenuItemHeaderDelete {
            get {
                return ResourceManager.GetString("MenuItemHeaderDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string MenuItemHeaderExit {
            get {
                return ResourceManager.GetString("MenuItemHeaderExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Above.
        /// </summary>
        public static string MenuItemHeaderInsertAbove {
            get {
                return ResourceManager.GetString("MenuItemHeaderInsertAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Below.
        /// </summary>
        public static string MenuItemHeaderInsertBelow {
            get {
                return ResourceManager.GetString("MenuItemHeaderInsertBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open....
        /// </summary>
        public static string MenuItemHeaderOpen {
            get {
                return ResourceManager.GetString("MenuItemHeaderOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O_pen Recent.
        /// </summary>
        public static string MenuItemHeaderOpenRecent {
            get {
                return ResourceManager.GetString("MenuItemHeaderOpenRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        public static string MenuItemHeaderSave {
            get {
                return ResourceManager.GetString("MenuItemHeaderSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save _As....
        /// </summary>
        public static string MenuItemHeaderSaveAs {
            get {
                return ResourceManager.GetString("MenuItemHeaderSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Variables.
        /// </summary>
        public static string PageHeaderGlobalVariables {
            get {
                return ResourceManager.GetString("PageHeaderGlobalVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapons.
        /// </summary>
        public static string PageHeaderWeapons {
            get {
                return ResourceManager.GetString("PageHeaderWeapons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save on exit.
        /// </summary>
        public static string SaveOnExit {
            get {
                return ResourceManager.GetString("SaveOnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load failed!.
        /// </summary>
        public static string StatusTextFileLoadFail {
            get {
                return ResourceManager.GetString("StatusTextFileLoadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load successful..
        /// </summary>
        public static string StatusTextFileLoadSuccess {
            get {
                return ResourceManager.GetString("StatusTextFileLoadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file loaded..
        /// </summary>
        public static string StatusTextFileNotLoaded {
            get {
                return ResourceManager.GetString("StatusTextFileNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save failed!.
        /// </summary>
        public static string StatusTextFileSaveFail {
            get {
                return ResourceManager.GetString("StatusTextFileSaveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save successful..
        /// </summary>
        public static string StatusTextFileSaveSuccess {
            get {
                return ResourceManager.GetString("StatusTextFileSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded symbols from {0}..
        /// </summary>
        public static string StatusTextSymbolsLoaded {
            get {
                return ResourceManager.GetString("StatusTextSymbolsLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved symbols to {0}..
        /// </summary>
        public static string StatusTextSymbolsSaved {
            get {
                return ResourceManager.GetString("StatusTextSymbolsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the GTA:LCS Save Editor!.
        /// </summary>
        public static string StatusTextWelcome {
            get {
                return ResourceManager.GetString("StatusTextWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the log when the application exits..
        /// </summary>
        public static string ToolTipSaveOnExit {
            get {
                return ResourceManager.GetString("ToolTipSaveOnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file is compatible with {0}..
        /// </summary>
        public static string ToolTipTextFileCompatibility {
            get {
                return ResourceManager.GetString("ToolTipTextFileCompatibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file has unsaved changes..
        /// </summary>
        public static string ToolTipTextFileModified {
            get {
                return ResourceManager.GetString("ToolTipTextFileModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assault.
        /// </summary>
        public static string WeaponSlotAssault {
            get {
                return ResourceManager.GetString("WeaponSlotAssault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hand.
        /// </summary>
        public static string WeaponSlotHand {
            get {
                return ResourceManager.GetString("WeaponSlotHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy.
        /// </summary>
        public static string WeaponSlotHeavy {
            get {
                return ResourceManager.GetString("WeaponSlotHeavy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melee.
        /// </summary>
        public static string WeaponSlotMelee {
            get {
                return ResourceManager.GetString("WeaponSlotMelee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pistol.
        /// </summary>
        public static string WeaponSlotPistol {
            get {
                return ResourceManager.GetString("WeaponSlotPistol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projectile.
        /// </summary>
        public static string WeaponSlotProjectile {
            get {
                return ResourceManager.GetString("WeaponSlotProjectile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shotgun.
        /// </summary>
        public static string WeaponSlotShotgun {
            get {
                return ResourceManager.GetString("WeaponSlotShotgun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMG.
        /// </summary>
        public static string WeaponSlotSmg {
            get {
                return ResourceManager.GetString("WeaponSlotSmg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sniper.
        /// </summary>
        public static string WeaponSlotSniper {
            get {
                return ResourceManager.GetString("WeaponSlotSniper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special.
        /// </summary>
        public static string WeaponSlotSpecial {
            get {
                return ResourceManager.GetString("WeaponSlotSpecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string WindowTitleLog {
            get {
                return ResourceManager.GetString("WindowTitleLog", resourceCulture);
            }
        }
    }
}
