namespace LCSSaveEditor.Core
{
    public enum GlobalVariable
    {
        Null,           // not a variable, default value

        // saved global variables

        IntroMissionPassed = 6,
        _UnknownFlag, // mobile only
        PlayerX,
        PlayerY,
        PlayerZ,
        PadMode,
        Package1Collected,
        Package2Collected,
        Package3Collected,
        Package4Collected,
        Package5Collected,
        Package6Collected,
        Package7Collected,
        Package8Collected,
        Package9Collected,
        Package10Collected,
        Package11Collected,
        Package12Collected,
        Package13Collected,
        Package14Collected,
        Package15Collected,
        Package16Collected,
        Package17Collected,
        Package18Collected,
        Package19Collected,
        Package20Collected,
        Package21Collected,
        Package22Collected,
        Package23Collected,
        Package24Collected,
        Package25Collected,
        Package26Collected,
        Package27Collected,
        Package28Collected,
        Package29Collected,
        Package30Collected,
        Package31Collected,
        Package32Collected,
        Package33Collected,
        Package34Collected,
        Package35Collected,
        Package36Collected,
        Package37Collected,
        Package38Collected,
        Package39Collected,
        Package40Collected,
        Package41Collected,
        Package42Collected,
        Package43Collected,
        Package44Collected,
        Package45Collected,
        Package46Collected,
        Package47Collected,
        Package48Collected,
        Package49Collected,
        Package50Collected,
        Package51Collected,
        Package52Collected,
        Package53Collected,
        Package54Collected,
        Package55Collected,
        Package56Collected,
        Package57Collected,
        Package58Collected,
        Package59Collected,
        Package60Collected,
        Package61Collected,
        Package62Collected,
        Package63Collected,
        Package64Collected,
        Package65Collected,
        Package66Collected,
        Package67Collected,
        Package68Collected,
        Package69Collected,
        Package70Collected,
        Package71Collected,
        Package72Collected,
        Package73Collected,
        Package74Collected,
        Package75Collected,
        Package76Collected,
        Package77Collected,
        Package78Collected,
        Package79Collected,
        Package80Collected,
        Package81Collected,
        Package82Collected,
        Package83Collected,
        Package84Collected,
        Package85Collected,
        Package86Collected,
        Package87Collected,
        Package88Collected,
        Package89Collected,
        Package90Collected,
        Package91Collected,
        Package92Collected,
        Package93Collected,
        Package94Collected,
        Package95Collected,
        Package96Collected,
        Package97Collected,
        Package98Collected,
        Package99Collected,
        Package100Collected,
        Collected10Packages,
        Collected20Packages,
        Collected30Packages,
        Collected40Packages,
        Collected50Packages,
        Collected60Packages,
        Collected70Packages,
        Collected80Packages,
        Collected90Packages,
        AllPackagesCollected,
        CurrentTimeHours,
        // 123 unused
        CurrentTimeMinutes = 124,
        Weapon36Ammo,
        Weapon1Ammo,
        Weapon2Ammo,
        Weapon7Ammo,
        Weapon3Ammo,
        Weapon4Ammo,
        Weapon6Ammo,
        Weapon8Ammo,
        Weapon10Ammo,
        Weapon5Ammo,
        Weapon9Ammo,
        Weapon11Ammo,
        Weapon12Ammo,
        Weapon15Ammo,
        Weapon14Ammo,
        Weapon13Ammo,
        Weapon17Ammo,
        Weapon18Ammo,
        Weapon19Ammo,
        Weapon20Ammo,
        Weapon21Ammo,
        Weapon22Ammo,
        Weapon23Ammo,
        Weapon24Ammo,
        Weapon25Ammo,
        Weapon27Ammo,
        Weapon26Ammo,
        Weapon30Ammo,
        Weapon32Ammo,
        Weapon31Ammo,
        Weapon33Ammo,
        Weapon28Ammo,
        Weapon29Ammo,
        // 158 unused
        PlayerWeapon = 159,
        PlayerWantedLevel,
        PlayerArmor,
        PlayerMoney,
        PlayerHeading,
        Rampage1Passed,
        Rampage2Passed,
        Rampage3Passed,
        Rampage4Passed,
        Rampage5Passed,
        Rampage6Passed,
        Rampage7Passed,
        Rampage8Passed,
        Rampage9Passed,
        Rampage10Passed,
        Rampage11Passed,
        Rampage12Passed,
        Rampage13Passed,
        Rampage14Passed,
        Rampage15Passed,
        Rampage16Passed,
        Rampage17Passed,
        Rampage18Passed,
        Rampage19Passed,
        Rampage20Passed,
        StuntJump1Completed,
        StuntJump2Completed,
        StuntJump3Completed,
        StuntJump4Completed,
        StuntJump5Completed,
        StuntJump6Completed,
        StuntJump7Completed,
        StuntJump8Completed,
        StuntJump9Completed,
        StuntJump10Completed,
        StuntJump11Completed,
        StuntJump12Completed,
        StuntJump13Completed,
        StuntJump14Completed,
        StuntJump15Completed,
        StuntJump16Completed,
        StuntJump17Completed,
        StuntJump18Completed,
        StuntJump19Completed,
        StuntJump20Completed,
        StuntJump21Completed,
        StuntJump22Completed,
        StuntJump23Completed,
        StuntJump24Completed,
        StuntJump25Completed,
        StuntJump26Completed,
        StuntJumpBaseReward,
        PhilsGunShopUnlocked,
        CurrentInterior,
        AllRampagesPassed,
        AllStuntJumpsCompleted,
        VigilanteMissionCompleted,
        AmbulanceMissionCompleted,
        FirefighterMissionCompleted,
        TaxiMissionCompleted,
        TaxiFaresDroppedOff,
        // 220 unused
        // 221 unused
        // 222 unused
        RcRace1Completed = 223,
        RcRace2Completed,
        RcRace3Completed,
        RadioAnnouncement0Status,
        RadioAnnouncement1Status,
        RadioAnnouncement2Status,
        RadioAnnouncement3Status,
        RadioAnnouncement4Status,
        RadioAnnouncement5Status,
        RadioAnnouncement6Status,
        RadioAnnouncement7Status,
        RadioAnnouncement8Status,
        RadioAnnouncement9Status,
        RadioAnnouncement10Status,
        RadioAnnouncement11Status,
        RadioAnnouncement12Status,
        RadioAnnouncement13Status,
        VicContactAvailable,
        AllVicMissionsPassed,
        VicMission,
        SalContactAvailable,
        AllSalMissionsPassed,
        SalMission,
        JdtContactAvailable,
        AllJdtMissionsPassed,
        JdtMission,
        MacContactAvailable,
        AllMacMissionsPassed,
        MacMission,
        MarContactAvailable,
        AllMarMissionsPassed,
        MarMission,
        Jdt5Status, // TODO: play with these, mission prereqs?
        Mac6Status,
        Sal6Status,
        Mar5Status,
        Vic7Status,
        Sal5Status, // END TODO
        AllAngMissionsCompleted,
        AngPortlandCompleted,
        AngStauntonCompleted,
        AngShoresideCompleted,
        // 265 unused
        Tr1Completed = 266,
        CarsaleStatus,
        CarsaleCompleted,
        // 269 unused
        // 270 unused
        // 271 unused
        // 272 unused
        CarsaleLevel = 273,
        RcBomb1Completed,
        RcBomb1HighScore,
        TvCompleted,
        NoodleCompleted,
        KickstHighScore,
        KickstCompleted1,
        KickstCompleted2,
        Tp1HighScore,
        Tp1Completed,
        Tp2HighScore,
        Tp2Completed,
        // 285 unused
        Ts1HighScore = 286,
        Ts1Completed,
        UnderwearCostumeUnlocked,
        CoxCostumeUnlocked,
        HeroCostumeUnlocked,
        CarsaleAssetPickupValue,
        BikesaleAssetPickupValue,
        NoodleAssetPickupValue,
        PizzaAssetPickupValue,
        SalsContactAvailable,
        AllSalsMissionsPassed,
        SalsMission,
        RaysContactAvailable,
        AllRaysMissionsPassed,
        RaysMission,
        DonsContactAvailable,
        AllDonsMissionsPassed,
        DonsMission,
        NedsContactAvailable,
        AllNedsMissionsPassed,
        NedsMission,
        _307, // TODO: play with these, mission prereqs?
        _308,
        _309,
        _310,
        _311,
        _312,
        _313,
        _314,
        _315,
        _316, // END TODO
        PcjPlayCompleted,
        CrashCompleted,
        // 319-348 unused
        Rac1DontIncrementMissionAttempts = 349,
        Rac2DontIncrementMissionAttempts,
        Rac3DontIncrementMissionAttempts,
        Bik1DontIncrementMissionAttempts,
        Bik2DontIncrementMissionAttempts,
        Bik3DontIncrementMissionAttempts,
        // 355 unused
        // 356 unused
        // 357 unused
        // 358 unused
        // 359 unused
        // 360 unused
        RcRace1FastestTime = 361,
        RcRace2FastestTime,
        RcRace3FastestTime,
        RcRace1Level,
        RcRace2Level,
        RcRace3Level,
        CrashHighScore,
        Tt1FastestTime,
        Tt2FastestTime,
        Tt3FastestTime,
        Tt4FastestTime,
        Tt5FastestTime,
        Tt6FastestTime,
        Tt7FastestTime,
        Tt8FastestTime,
        Tt9FastestTime,
        Tt10FastestTime,
        Tt1BestLap,
        Tt2BestLap,
        Tt3BestLap,
        Tt4BestLap,
        Tt5BestLap,
        Tt6BestLap,
        Tt7BestLap,
        Tt8BestLap,
        Tt9BestLap,
        Tt10BestLap,
        // 388 unused
        // 389 unused
        Tt1TargetTimeBeat = 390,
        Tt2TargetTimeBeat,
        Tt3TargetTimeBeat,
        Tt4TargetTimeBeat,
        Tt5TargetTimeBeat,
        Tt6TargetTimeBeat,
        Tt7TargetTimeBeat,
        Tt8TargetTimeBeat,
        Tt9TargetTimeBeat,
        DirtBikeMostAir,
        Tt10TargetTimeBeat,
        Tt1Completed,
        Tt2Completed,
        Tt3Completed,
        Tt4Completed,
        Tt5Completed,
        Tt6Completed,
        Tt7Completed,
        Tt8Completed,
        Tt9Completed,
        Tt10Completed,
        // 411-420 not saved
        ImportHelpPickedUp = 421,
        ImportCar1Delivered,
        ImportCar2Delivered,
        ImportCar3Delivered,
        ImportCar4Delivered,
        ImportCar5Delivered,
        ImportCar6Delivered,
        ImportCar7Delivered,
        ImportCar8Delivered,
        ImportCar9Delivered,
        ImportCar10Delivered,
        ImportCar11Delivered,
        ImportCar12Delivered,
        ImportCar13Delivered,
        ImportCar14Delivered,
        ImportCar15Delivered,
        ImportCar16Delivered,
        BikesaleStatus,
        BikesaleCompleted,
        BikesaleNumFreewaysSold,
        BikesaleNumPcjsSold,
        BikesaleNumFaggiosSold,
        BikesaleNumSanchezsSold,
        PizzaCompleted,
        SalhContactAvailable,
        AllSalhMissionsCompleted,
        SalhMission,
        DonhContactAvailable,
        AllDonhMissionsCompleted,
        DonhMission,
        ToshContactAvailable,
        AllToshMissionsCompleted,
        ToshMission,
        _454, // TODO: play with these, mission prereqs?
        _455,
        _456,
        _457,
        _458,
        _459, // END TODO
        TouristCompleted,
        TouristMission,
        TouristPrevMission,
        // 463 unused
        HelpThreadStarted = 464,
        BikeHelpShown,
        SprintHelpShown,
        // 467 unused
        CameraHelpShown = 468,
        _UnknownMaybeInfoPickup1,
        WantedHelpShown,
        _UnknownMaybeInfoPickup2,
        _UnknownMaybeInfoPickup3,
        DriveByHelpShown,
        DriveByBikeHelpShown,
        // 475 unused
        BribeHelpShown = 476,
        // 477 unused
        MrBenzInfoShown = 478,
        CarsaleInfoShown,
        SirenHelpShown,
        HitmanInfoShown,
        RaceInfoShown,
        BikInfoShown,
        CrashInfoShown,
        TankHelpShown,
        M60InfoShown,
        InfoPickup1Collected,
        InfoPickup2Collected,
        InfoPickup3Collected,
        InfoPickup4Collected,
        InfoPickup5Collected,
        InfoPickup6Collected,
        InfoPickup7Collected,
        InfoPickup8Collected,
        InfoPickup9Collected,
        InfoPickup10Collected,
        InfoPickup11Collected,
        InfoPickup12Collected,
        InfoPickup13Collected,
        InfoPickup14Collected,
        OneHundredPercentInfoShown,
        MultiplayerInfo1Shown,
        MultiplayerInfo2Shown,
        MultiplayerInfo3Shown,
        MultiplayerInfo4Shown,
        ExplosiveHelpShown,
        WeaponCycleHelpShown,
        HandbrakeHelpShown,
        MinigunInfoShown,
        // 510 unused
        MicroSmgInfoShown = 511,
        PhilInfoShown,
        MinigunInfo2Shown,
        PortlandSafehouseUnlocked,
        StauntonSafehouseUnlocked,
        ShoresideSafehouseUnlocked,
        CameraModeOnFoot,
        Outfit1Unlocked,
        Outfit2Unlocked,
        Outfit3Unlocked,
        Outfit4Unlocked,
        Outfit5Unlocked,
        Outfit6Unlocked,
        Outfit7Unlocked,
        Outfit8Unlocked,
        Outfit9Unlocked,
        Outfit10Unlocked,
        Outfit11Unlocked,
        Outfit12Unlocked,
        Outfit13Unlocked,
        Outfit14Unlocked,
        Outfit15Unlocked,
        Outfit16Unlocked,
        PlayerOutfit,
        _UnknownAmbhit,
        _UnknownSalh5,
        // 537-1265 not saved
        GarageSpray1 = 1266,
        Garage1,
        Garage2,
        Garage3,
        // 1270 unused
        // 1271 unused
        // 1272 unused
        GarageCrusher = 1273,
        GarageBomb1,
        GarageHideout1,
        GarageHideout2,
        GarageHideout3,
        // 1278 not saved
        // 1279 not saved
        // 1280 not saved
        // 1281 not saved
        // 1282 not saved
        // 1283 not saved
        // 1284 not saved
        GarageSpray2 = 1285,
        GarageBomb2,
        Garage11,
        Garage12,
        Garage13,
        Garage14,
        GarageImport,
        // 1292 not saved
        // 1293 not saved
        // 1294 not saved
        // 1295 not saved
        Garage16 = 1296,
        Garage17,

        // end of saved variables
    }
}
