//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHampson.LcsSaveEditor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WHampson.LcsSaveEditor.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save your changes?.
        /// </summary>
        public static string DialogTextFileSavePrompt {
            get {
                return ResourceManager.GetString("DialogTextFileSavePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string DialogTitleError {
            get {
                return ResourceManager.GetString("DialogTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save File?.
        /// </summary>
        public static string DialogTitleFileSavePrompt {
            get {
                return ResourceManager.GetString("DialogTitleFileSavePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConvertBack is not supported for this converter..
        /// </summary>
        public static string ExceptionMessageConvertBackNotSupported {
            get {
                return ResourceManager.GetString("ExceptionMessageConvertBackNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} savedata files are not supported at this time..
        /// </summary>
        public static string ExceptionMessageFileTypeNotSupported {
            get {
                return ResourceManager.GetString("ExceptionMessageFileTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The block size in the header does not match the number of available bytes in the stream..
        /// </summary>
        public static string ExceptionMessageIncorrectBlockSize {
            get {
                return ResourceManager.GetString("ExceptionMessageIncorrectBlockSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect block tag - &apos;{0}&apos;. Expected &apos;{1}&apos;..
        /// </summary>
        public static string ExceptionMessageInvalidBlockTag {
            get {
                return ResourceManager.GetString("ExceptionMessageInvalidBlockTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid GTA:LCS savedata file..
        /// </summary>
        public static string ExceptionMessageInvalidSaveData {
            get {
                return ResourceManager.GetString("ExceptionMessageInvalidSaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple calls to this function are not supported..
        /// </summary>
        public static string ExceptionMessageMultipleCallsNotSupported {
            get {
                return ResourceManager.GetString("ExceptionMessageMultipleCallsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You weren&apos;t supposed to be able to get here, you know..
        /// </summary>
        public static string ExceptionMessageOops {
            get {
                return ResourceManager.GetString("ExceptionMessageOops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load file!.
        /// </summary>
        public static string MessageFileLoadFailed {
            get {
                return ResourceManager.GetString("MessageFileLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File loaded successfully..
        /// </summary>
        public static string MessageFileLoadSuccessful {
            get {
                return ResourceManager.GetString("MessageFileLoadSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file loaded..
        /// </summary>
        public static string MessageFileNotLoaded {
            get {
                return ResourceManager.GetString("MessageFileNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save file!.
        /// </summary>
        public static string MessageFileSaveFailed {
            get {
                return ResourceManager.GetString("MessageFileSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File saved successfully..
        /// </summary>
        public static string MessageFileSaveSuccessful {
            get {
                return ResourceManager.GetString("MessageFileSaveSuccessful", resourceCulture);
            }
        }
    }
}
